# Generated by Django 3.2.5 on 2021-07-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_writer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='released_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
