# Generated by Django 3.2.5 on 2021-08-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default-profile.jpg', upload_to=''),
        ),
    ]
