# Generated by Django 3.2.5 on 2021-08-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/images/default-profile.jpg', null=True, upload_to='static/images/'),
        ),
    ]
