# Generated by Django 3.2.5 on 2021-08-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20210805_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
