# Generated by Django 3.2.5 on 2021-08-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20210806_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-released_date']},
        ),
    ]
