# Generated by Django 3.2.5 on 2021-08-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_alter_article_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='released_date',
            field=models.DateField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
