# Generated by Django 3.2.5 on 2021-08-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='profile_picture',
        ),
    ]
