# Generated by Django 3.2.5 on 2021-08-16 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_remove_article_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='_user',
        ),
    ]
