# Generated by Django 3.2.5 on 2021-08-19 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_comment_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created']},
        ),
    ]
